echo "> Installing all Go dependencies..."
$GOROOT/bin/go get "gopkg.in/mgo.v2"
$GOROOT/bin/go get "gopkg.in/mgo.v2/bson"
$GOROOT/bin/go get "github.com/gin-gonic/gin"
echo "> All Go dependencies was installed"